# Generated by Django 4.2.5 on 2023-09-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_hospital_medicalrecord_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
